### ISSUE TITLE
[Feature Request] Custom main menu GUI scale

### ISSUE THREAD

**Issue by MicrocontrollersDev** [Noxiuam/MainMenus#1]
I play with a somewhat small GUI scale, which works fine with the vanilla menu since the buttons are pretty large, but this can be an issue when using a custom menu as they aren't scaled as well for my GUI. An option to force the main menu to render at a higher scale would be great to make the buttons easier to read and press.

**Comment by Noxiuam** [comment]
I was originally going to say no to this, however I have made a breakthrough with how the scaling system works.

The only problem you would have to deal with is the font renderer being distorted due to it not being made for the scale:

![Screenshot 2023-02-06 163732](https://user-images.githubusercontent.com/96212795/217095330-9a822fcf-606b-4987-b601-b76aaa8cdc39.png)
![Screenshot 2023-02-06 163714](https://user-images.githubusercontent.com/96212795/217095335-7e1552ed-b86b-4c9e-9eb8-8f13208297ba.png)
![Screenshot 2023-02-06 163604](https://user-images.githubusercontent.com/96212795/217095336-8e4f3bfe-8cba-4b0a-bb80-93a5aa0f61e0.png)

**Comment by MicrocontrollersDev** [comment]
Perfectly fine with me

**Comment by Noxiuam** [comment]
Most I can do is make it go based off your MC gui scale, any others would just be unpredictable. Is that fine?

**Comment by MicrocontrollersDev** [comment]
I think so? Not entirely sure what that means to be honest.

**Comment by Noxiuam** [comment]
> Most I can do is make it go based off your MC gui scale, any others would just be unpredictable. Is that fine?

End result on Large btw:
![2023-02-06_17 10 27](https://user-images.githubusercontent.com/96212795/217099469-24ff88b8-72ba-4798-8366-d56c5e88a0fc.png)

**Comment by Noxiuam** [comment]
> I think so? Not entirely sure what that means to be honest.

When you change your GUI Scale in MC's settings, the menus will update with that accordingly.

**Comment by MicrocontrollersDev** [comment]
Is that not already how that works?

**Comment by Noxiuam** [comment]
> Is that not already how that works?

no, it forces Normal to avoid the scaling problems, but I made it update based on the scale you set it to

**Comment by MicrocontrollersDev** [comment]
I’m on release 1.1 right now and the scale already changes when I change my GUI scale. Not sure if I’m misunderstanding something

**Comment by Noxiuam** [comment]
> I’m on release 1.1 right now and the scale already changes when I change my GUI scale. Not sure if I’m misunderstanding something

The main menu scale changes?

**Comment by MicrocontrollersDev** [comment]
Ah, I lied. Only on Auto

**Comment by Noxiuam** [comment]
Ahh wait I completely misinterpreted what was being requested, so a slider that forces the scale? (Just so I am making sure I understand correctly)

**Comment by MicrocontrollersDev** [comment]
> Ahh wait I completely misinterpreted what was being requested, so a slider that forces the scale? (Just so I am making sure I understand correctly)

Exactly, independent of what the GUI scale is actually set to. Similar to Patcher’s custom GUI scaling for the inventory only

**Comment by Noxiuam** [comment]
I see now, let me do some tweaking.

**Comment by Noxiuam** [comment]
Try the latest release and see that is for you.

https://github.com/Noxiuam/MainMenus/releases/tag/1.2.0

**Comment by MicrocontrollersDev** [comment]
perfect! thanks!
